name: lpshipit # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Helpful utility for merging launchpad MPs (only works for git repos) # 79 char long summary
description: |
  Helpful utility for merging launchpad MPs (only works for git repos)

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  lpshipit:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - git
      - python3-launchpadlib

apps:
  lpshipit:
    command: env LC_ALL=C.UTF-8 ${SNAP}/bin/lpshipit
    plugs:
      - home
      - network
