name: lpshipit # you probably want to 'snapcraft register <name>'
version: '0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Helpful utility for merging and testing launchpad MPs # 79 char long summary
description: |
  Helpful utility for mergingand testing launchpad MPs (only works for git repos)

grade: stable
confinement: classic

parts:
  lpshipit:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - git
      - python3-launchpadlib

apps:
  lpshipit:
    command: ./bin/lpshipit
  lpmpmessage:
    command: ./bin/lpmpmessage
  lpmptox:
    command: ./bin/lpmptox

