name: lpshipit # you probably want to 'snapcraft register <name>'
version: '0.4.7' # just for humans, typically '1.2+git' or '1.3.2'
summary: Helpful utility for merging and testing launchpad MPs # 79 char long summary
description: |
  Helpful utility for mergingand testing launchpad MPs (only works for git repos)

grade: stable
confinement: classic

parts:
  lpshipit:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - git
      - python3-launchpadlib
  lpshipit-wrappers:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x lpshipit_wrapper
      chmod +x lpmpmessage_wrapper
      chmod +x lpmptox_wrapper
      snapcraftctl build
    stage:
      - usr/bin/lpshipit_wrapper
      - usr/bin/lpmpmessage_wrapper
      - usr/bin/lpmptox_wrapper
    organize:
      lpshipit_wrapper: usr/bin/lpshipit_wrapper
      lpmpmessage_wrapper: usr/bin/lpmpmessage_wrapper
      lpmptox_wrapper: usr/bin/lpmptox_wrapper
apps:
  lpshipit:
    command: usr/bin/lpshipit_wrapper
  lpmpmessage:
    command: usr/bin/lpmpmessage_wrapper
  lpmptox:
    command: usr/bin/lpmptox_wrapper

